version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
    networks:
      - app-network

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
